export const  GET_ALL_TODO = 'get_all_todo'
export const  DEL_ONE_TODO = 'del_one_todo'
export const  CHANGE_ONE_TODO = 'change_one_todo'
export const  ADD_ONE_TODO = 'add_one_todo'
export const  DEL_FINISHED_TODO = 'del_finished_todo'
export const  IS_CHECKED_ALL_TODO = 'is_checked_all_todo'